### ISSUE TITLE
Next episode option

### ISSUE THREAD

**Issue by POMATu** [POMATu/anime-tool#3]
Save options with latest episode and all arguments to text file in profile folder. Cause I always forget what episode number I watched yesterday and have to bruteforce that.

**Comment by POMATu** [comment]
next, previous, last options to see +1, -1, or last watched episode

**Comment by captaincolonelfox** [comment]
```
my %anime = (
	'09' => 'Wangan Midnight - 09 [DVDRip 1280x720 x264 AC3]',
	'08' => 'Wangan Midnight - 08 [DVDRip 1280x720 x264 AC3]',
	'06' => 'Wangan Midnight - 06 [DVDRip 1280x720 x264 AC3]',
	'07' => 'Wangan Midnight - 07 [DVDRip 1280x720 x264 AC3]',
	'11' => 'Wangan Midnight - 11 [DVDRip 1280x720 x264 AC3]',
	'10' => 'Wangan Midnight - 10 [DVDRip 1280x720 x264 AC3]'
);

my @sorted_episodes = sort keys %anime;

my $first_episode_name = $anime{$sorted_episodes[0]};

print $first_episode_name;
```
Give me following output:
`Wangan Midnight - 06 [DVDRip 1280x720 x264 AC3]`
So, can it be helpful?

**Comment by POMATu** [comment]
after this I think that my code should be commited to dailywtf, lol.

But that's working just for first episode, not for next episode after 5th and etc. So the problem that's we are loosing some link to the data when converting hash to array. That link can be restored by reiterating over arrays again. That's why I am not doing that anywhere cause hash give some kind of good connection between 2 string variables.

**Comment by captaincolonelfox** [comment]
@POMATu 
Never heard about it :D

Uhm, quite not get it.
We use array as sorted episode storage and when we need convert our episode to actual link - we use hash. Seems pretty solid to me.

We have sorted array `['05', '06', '07', '08', '09']` and you can move around with index `arr[current+1]`, `arr[current-1]` to get episode you want.
Then you use `hash` to get actual name `hash{episode_number}`.

My point that you don't even need this linked data until some point in time, because all you do - is working with episode numbers. And when we executing command - then we convert it to episode name.
1. We load hash - now forget about names
2. Take keys, use them as we want
3. Convert them back

UPD: You can get counter `current` from array 
```
use List::MoreUtils qw(first_index);
my $index = first_index { $_ eq $passed_episode_number } @sorted_episodes;
```

**Comment by POMATu** [comment]
Yeah you may be right, I'm just tired and when I'm tired my code is like I'm high maybe even less clear.

**Comment by captaincolonelfox** [comment]
@POMATu 
Yep, I know, we spend all day on it :D
It was fun, btw. Actually, we can move to telegram ([SCRUBBED]) or other messenger if you want to continue working on it.

**Comment by captaincolonelfox** [comment]
@POMATu 
After thinking about #12 I imagine saving episodes as:
1. Main programm loop through passed episodes
2. For each it starts mpv and save current episode with all path variables (making `watch($episode)` subroutine may be a good decision) 
3. Then going back to loop

**Comment by POMATu** [comment]
issue related to obsolete version
